theme: jekyll-theme-slate
title: <center>Welcome To </center>
title: <center> Dominick DiTucci's Homepage!</center>
description: <center>Feel free to check out my projects and keep coming back to see what's new</center>
