theme: jekyll-theme-merlot
title: <h2 style="color:white;"><center>Welcome To </center></h2>
description: <h2 style="color:white;"><center>Dominick DiTucci's Homepage!</center></h2><br><center><h3 style="color:white;">Feel free to check out my projects and keep coming back to see what's new</center></h3>
